### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by linojon** [gerhardsletten/react-reader#92] opened 2021-07-27 21:25 UTC
hello, i'm trying to use this package with a Next.js project. I get the following error in my project. So I created a new project and get the same error,
```
yarn create next-app --typescript
```
added the package, and created a simple page. It fails on the import (even without using the ReactReader component), with this error
```
D:\Documents\JavascriptProjects\epubtest\node_modules\epubjs\libs\mime\mime.js:169
export default { lookup };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Documents\JavascriptProjects\epubtest\node_modules\epubjs\lib\resources.js:16:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```
I tried adding a .babelrc file
```
{
    "presets": ["next/babel"],
    "plugins": []
  }
```
and other things. I'm stumped.

**Comment by gerhardsletten** [comment] 2021-08-03 08:08
@linojon Duplicate of #72 - see it for solution

**Closed by gerhardsletten** 2021-08-03 08:08 UTC
